# Generated by Django 3.2.4 on 2021-06-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('email', models.CharField(blank=True, max_length=224, null=True)),
                ('phone', models.CharField(blank=True, max_length=224, null=True)),
                ('username', models.CharField(blank=True, max_length=224, null=True)),
                ('password', models.CharField(blank=True, max_length=224, null=True)),
                ('role', models.IntegerField(blank=True, null=True)),
                ('rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
