# Generated by Django 3.2.4 on 2021-06-17 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('des', models.CharField(blank=True, max_length=224, null=True)),
                ('road', models.CharField(blank=True, max_length=224, null=True)),
                ('ward', models.CharField(blank=True, max_length=224, null=True)),
                ('province', models.CharField(blank=True, max_length=224, null=True)),
                ('city', models.CharField(blank=True, max_length=224, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fullname',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fName', models.CharField(blank=True, max_length=224, null=True)),
                ('mName', models.CharField(blank=True, max_length=224, null=True)),
                ('lName', models.CharField(blank=True, max_length=224, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='addr',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='client.address'),
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='client.fullname'),
        ),
    ]
