# Generated by Django 3.2.4 on 2021-06-17 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0003_auto_20210618_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(blank=True, default='', max_length=224, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='des',
            field=models.CharField(blank=True, default='', max_length=224, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='province',
            field=models.CharField(blank=True, default='', max_length=224, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='road',
            field=models.CharField(blank=True, default='', max_length=224, null=True),
        ),
        migrations.AlterField(
            model_name='address',
            name='ward',
            field=models.CharField(blank=True, default='', max_length=224, null=True),
        ),
        migrations.AlterField(
            model_name='fullname',
            name='fName',
            field=models.CharField(blank=True, default='', max_length=224, null=True),
        ),
        migrations.AlterField(
            model_name='fullname',
            name='id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='fullname',
            name='lName',
            field=models.CharField(blank=True, default='', max_length=224, null=True),
        ),
        migrations.AlterField(
            model_name='fullname',
            name='mName',
            field=models.CharField(blank=True, default='', max_length=224, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='addr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=224, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.fullname'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(blank=True, default='', max_length=224, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=224, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', max_length=224, null=True),
        ),
    ]
