# Generated by Django 3.2.4 on 2021-06-17 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='addr',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='client.address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='client.fullname'),
        ),
    ]
