# Generated by Django 3.2.4 on 2021-06-17 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20210618_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='addr',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.address'),
        ),
    ]
