# Generated by Django 3.2.4 on 2021-06-17 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0007_alter_user_addr'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=224, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=224, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('rate', models.IntegerField(default=0)),
                ('attrs', models.ManyToManyField(related_name='attr_cate', to='client.Attribute')),
            ],
        ),
    ]
