# Generated by Django 3.2.4 on 2021-06-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0015_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='des',
            field=models.CharField(default='', max_length=224),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.CharField(default='', max_length=224),
        ),
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.FloatField(default='', max_length=224),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(default='', max_length=224),
        ),
        migrations.AlterField(
            model_name='product',
            name='os',
            field=models.CharField(default='', max_length=224),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(default='', max_length=224),
        ),
        migrations.AlterField(
            model_name='product',
            name='screen',
            field=models.FloatField(default='', max_length=224),
        ),
    ]
