# Generated by Django 3.2.4 on 2021-06-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0016_auto_20210619_0414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='memory',
            field=models.FloatField(default=0, max_length=224),
        ),
    ]
