# Generated by Django 3.2.4 on 2021-06-18 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0018_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.rating'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='attrs',
            field=models.ManyToManyField(blank=True, null=True, related_name='attr_cate', to='client.Attribute'),
        ),
    ]
