# Generated by Django 3.2.4 on 2021-06-19 08:18

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0020_auto_20210619_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=224)),
                ('createDate', models.DateTimeField(default='')),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('attrs', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=50, null=True), size=None)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.user')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('type', models.IntegerField(default=0)),
                ('bank', models.CharField(default='', max_length=224)),
                ('total', models.FloatField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='attribute',
            name='name',
            field=models.CharField(default='', max_length=224),
        ),
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('type', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('note', models.CharField(default='', max_length=224)),
                ('addr', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.address')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=224)),
                ('createDate', models.DateTimeField(default='')),
                ('like', models.IntegerField(default=0)),
                ('dislike', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.user')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.comment')),
            ],
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('quanity', models.IntegerField(default=0)),
                ('sale', models.FloatField(default=0)),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='client.product')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('createDate', models.DateTimeField(default='')),
                ('total', models.FloatField(default=0)),
                ('sale', models.FloatField(default=0)),
                ('status', models.IntegerField(default=0)),
                ('client', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.user')),
                ('pay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.payment')),
                ('ship', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='client.shipment')),
            ],
        ),
    ]
