# Generated by Django 3.2.4 on 2021-06-19 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0021_auto_20210619_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='attrs',
        ),
    ]
