# Generated by Django 3.2.4 on 2021-06-19 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0023_comment_prod'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='name',
            new_name='content',
        ),
    ]
