# Generated by Django 3.2.4 on 2021-06-19 17:40

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0024_auto_20210619_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='createDate',
            field=models.DateTimeField(default=datetime.date(2021, 6, 20)),
        ),
        migrations.AlterField(
            model_name='order',
            name='createDate',
            field=models.DateTimeField(default=datetime.date(2021, 6, 20)),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.payment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ship',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='client.shipment'),
        ),
        migrations.AlterField(
            model_name='reply',
            name='createDate',
            field=models.DateTimeField(default=datetime.date(2021, 6, 20)),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', max_length=224),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=224),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(default='', max_length=224),
        ),
        migrations.AlterField(
            model_name='user',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='', max_length=224),
        ),
    ]
