# Generated by Django 3.2.4 on 2021-06-19 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0025_auto_20210620_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='client.order'),
            preserve_default=False,
        ),
    ]
