# Generated by Django 3.2.4 on 2021-06-19 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0026_orderproduct_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='note',
            field=models.CharField(default='', max_length=224),
        ),
    ]
