# Generated by Django 3.2.4 on 2021-06-20 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0030_auto_20210620_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='type',
        ),
    ]
