# Generated by Django 3.2.4 on 2021-06-20 10:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0032_alter_order_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='createDate',
            field=models.DateField(default=datetime.date(2021, 6, 20)),
        ),
        migrations.AlterField(
            model_name='order',
            name='createDate',
            field=models.DateField(default=datetime.date(2021, 6, 20)),
        ),
        migrations.AlterField(
            model_name='reply',
            name='createDate',
            field=models.DateField(default=datetime.date(2021, 6, 20)),
        ),
    ]
